version: '3.1'
services:
  laypa:
    image: 'docker.laypa'
    command: 'flask run'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: 'laypa'
    ports:
      - '5000:5000'
    environment:
      LAYPA_MAX_QUEUE_SIZE: 128
      LAYPA_MODEL_BASE_PATH: /home/rutger/src/laypa-models/
      LAYPA_OUTPUT_BASE_PATH: /tmp/output/laypa/
      FLASK_DEBUG: 'true'
      FLASK_APP: 'api.app.py'
      FLASK_RUN_HOST: '0.0.0.0'
    volumes:
      - '/home/rutger/src/laypa-models/:/home/rutger/src/laypa-models/'
      - '/tmp/output/laypa:/tmp/output/laypa'
    networks:
      - pipeline
    shm_size: 512mb
    restart: always
  loghi-tooling:
    image: 'docker.loghi-tooling'
    command: '/src/loghi-tooling/loghiwebservice/target/appassembler/bin/LoghiWebserviceApplication server /home/rutger/src/loghi/webservice/loghi-tooling/configuration.yml'
    container_name: 'loghi-tooling'
    ports:
      - '8080:8080'
    environment:
      STORAGE_LOCATION: /tmp/upload
      P2PALA_CONFIG_FILE: /doesnotexist
      EXTRACT_BASELINES_MAX_THREADS: 4
      EXTRACT_BASELINES_QUEUE_LENGTH: 64
      CUT_FROM_IMAGE_MAX_THREADS: 4
      CUT_FROM_IMAGE_QUEUE_LENGTH: 64
      LOGHI_HTR_MERGE_PAGE_MAX_THREADS: 4
      LOGHI_HTR_MERGE_PAGE_QUEUE_LENGTH: 64
      RECALCULATE_READING_ORDER_NEW_MAX_THREADS: 4
      RECALCULATE_READING_ORDER_NEW_QUEUE_LENGTH: 64
      SPLIT_PAGE_TEXT_LINE_INTO_WORDS_MAX_THREADS: 4
      SPLIT_PAGE_TEXT_LINE_INTO_WORDS_QUEUE_LENGTH: 64
      DETECT_LANGUAGE_OF_PAGE_XML_MAX_THREADS: 4
      DETECT_LANGUAGE_OF_PAGE_XML_QUEUE_LENGTH: 64
    volumes: 
      - '/home/rutger/src/loghi/webservice/loghi-tooling/configuration.yml:/home/rutger/src/loghi/webservice/loghi-tooling/configuration.yml'
      - '/tmp/upload:/tmp/upload'
    networks:
      - pipeline
    shm_size: 512mb
    restart: always
  htr:
    image: 'docker.htr'
    command: 'python3 app.py'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: 'htr'
    ports:
      - '5001:5000'
    environment:
      FLASK_DEBUG: 'true'
      FLASK_APP: 'api.app.py'
      FLASK_RUN_HOST: '0.0.0.0'
    volumes:
      - '/home/rutger/src/loghi-htr-models/:/home/rutger/src/loghi-htr-models/'
      - '/tmp/output/loghi-htr:/tmp/output/loghi-htr'
    networks:
      - pipeline
    shm_size: 512mb
    restart: always
networks:
  pipeline:
